### ISSUE TITLE
Crash on move after brush.move sets selection to null.

### ISSUE THREAD

**Issue by mblandfo** [d3/d3-brush#15]
Reproduction is here: https://jsfiddle.net/sxrxaxrL/1/

Lines 76-81:

```
    if(x1 === x2){
    	//x2 = x1 + .1; // UNCOMMENT THIS TO FIX
    }
    var moveTo = [x(x1), x(x2)];
    console.log('move to = ' + moveTo);
    bg.call(brush.move, moveTo);   
```

Calling brush.move with x1 == x2 seems to work ok, but then in a d3 callback on a different call stack, it crashes:

d3.v4.js:12809 Uncaught TypeError: Cannot read property '0' of null

d3 source: (crash happens on the final line)

```
        selection = state.selection; // May be set by brush.move!

        if (lockX) w1 = selection[0][0], e1 = selection[1][0];
        if (lockY) n1 = selection[0][1], s1 = selection[1][1];

        if (selection[0][0] !== w1
```

If it's not allowed to call brush.move with x1 == x2, then at least it should throw an error immediately explaining this instead of later on a different call stack

**Comment by mbostock** [comment]
Yeah. The issue is that a degenerate (collapsed) selection is treated as the null selection within the context of *brush*.move. And then, if you set the selection to null while a brush gesture is active, it crashes. Probably the brush should ignore the externally-set selection in this case, changing this:

```js
selection = state.selection; // May be set by brush.move!
```

To this:

```js
if (state.selection) selection = state.selection; // May be set by brush.move!
```

**Comment by mbostock** [comment]
Regarding your test case, I’d also take a look at the [brush snapping examples](http://bl.ocks.org/mbostock/6232620). I’ve made a new [Brush Snapping III](http://bl.ocks.org/mbostock/b0d0aa4df3b5c3c0fa37d4b3f2127740) that shows how I’d implement your example.

**Comment by skipjack** [comment]
I'm seeing this issue as well with the latest `brush.clear(selection)` shorthand. I think it may have to do with my use of `brush.filter(() => d3.event.shiftKey)`.
