### ISSUE TITLE
small bug in the brush "snap" demo

### ISSUE THREAD

**Issue by Fil** [d3/d3-brush#19]
the demo at http://bl.ocks.org/mbostock/6232537 does not snap properly to a full day when you brush a small width

![bug](https://cloud.githubusercontent.com/assets/7001/18875734/478568b4-84c7-11e6-9866-a9e3aedc729c.gif)

changing line 74 seems to fix it:
```
-     d1[1] = d3.timeDay.offset(d0[1]);
+    d1[1] = d3.timeDay.ceil(d0[1]);
```

**Comment by mbostock** [comment]
It was supposed to be:

```js
d1[1] = d3.timeDay.offset(d1[0]);
```

I’ve fixed it.
