### ISSUE TITLE
Brush losing event handlers

### ISSUE THREAD

**Issue by zelitzsi** [d3/d3-brush#21]
I'm seeing a possibly related issue to #18, but not sure so filing separately. I modified the following b.lock to include start/end logging:

http://bl.ocks.org/zelitzsi/8b72cbd79863f04b5bcf7cb5d1e52320

If I brush in succession without letting the previous brush transition finish, I get the same 'start' event without 'end' event that #18 is seeing. However, this is repeatable across Firefox/Chrome on Mac. Interrupting the transition in this way breaks the brush - snapping doesn't occur and no brush events fire. Perhaps there is something about brush.move that breaks the previous transition?

**Comment by mbostock** [comment]
I broke *interrupt* events in d3-transition 1.0.2. I’ve fixed it and will push out a patch release later today. Thanks for the report.
