### ISSUE TITLE
Swap "e" and "w" resize controls to align DOM with actual view

### ISSUE THREAD

**Issue by zakimaksyutov** [d3/d3-brush#32]
Right now "east resize" goes first (example from v3 but v4 has the same order):

![image](https://user-images.githubusercontent.com/15914532/33737111-e9bcf35c-db49-11e7-9aaa-94b33fb1590c.png)

## Impact

When extending resize controls to be focusable, focus/screen reader still follows DOM order and as a result goes in reverse order:

![brush-taborder2](https://user-images.githubusercontent.com/15914532/33738818-726884c8-db4f-11e7-8fca-1d56aea9abeb.gif)

## Potential fix

Swap "e" and "w" in array of handles to align DOM order with actual view.

**Comment by mbostock** [comment]
Thanks for the suggestion and sorry for the delay! This has been fixed.
