### ISSUE TITLE
Brushing ordinal axis in d3 V4 parallel coordinate  ?

### ISSUE THREAD

**Issue by Abhijeet-Das** [d3/d3-brush#34]
I created a sample http://plnkr.co/edit/TiM6ZsvMTTBhh8ZdMoFQ?p=preview
for parallel coordinate in d3 V4. I am looking to brush the ordinal axis ( name column here). From the suggested changes in brush in V4, is that I need to use the invert function to get the corresponding data domain, but on brushing ordinal axis it says "invert is not a function" .

Could you please suggest some way to deal with this.
Thanks a lot for your time.

**Comment by mbostock** [comment]
Here’s what I would do for brushing a point scale:

https://observablehq.com/@d3/ordinal-brushing

Sorry for the delay getting back to you.
