### ISSUE TITLE
[Feature Request] Use transform attribute to position all shape elements instead of x and y attributes.

### ISSUE THREAD

**Issue by DimuDesigns** [d3/d3-brush#36]
While building custom handles for a brush I noticed an interesting side-effect where a custom handle is assigned an x and y attribute that automatically updates (relative to the brush extent) as long as the shape element has a "handle" class and an appropriate value for the "cursor" attribute. 

For shape elements such as **\<rect\>** or **\<circle\>** this side-effect is a boon as they support the x and y attribute (no need to set the position manually). However this does not hold for **\<path\>** elements which do not use x or y attributes according to the [SVG spec](https://www.w3.org/TR/SVG/paths.html#PathElement).  As a result, path-based shapes cannot benefit from these automatic position updates (which also affects the use of [**d3.symbol**](https://github.com/d3/d3-shape/blob/master/README.md#symbols) types since they are all path-based shapes). 

The current workaround (as seen in this [sample](https://bl.ocks.org/mbostock/4349545)) is to update the position of a custom handle in a brush event listener. 

But I think there is a better approach. What path elements do share with shape elements is a transform attribute. Replacing the x & y attributes with a translate transform would allow path elements to benefit from these automatic position updates relative to the brush selection's extents; removing the need to update position in an event handler.

--------------------------------------------------------

Another thing. When a child element of a brush (classed) element has children of its own; its position (x and y) attributes are not set. This becomes problematic with **\<g\>** elements where one might want to retain any automatic transformations applied at the group level. 

So in addition to generalizing  position updates by leveraging translate transforms, please retain transforms for child **\<g\>** elements contained within a brush classed element.

**Comment by mbostock** [comment]
Thanks for the suggestion. The rect elements also specify CSS cursors so that the cursor indicates how the gesture will be interpreted by the brush when you click. Also, the brush needs to set the width and height attributes of these default handles. Therefore I still think the cleanest approach for custom handles is to handle the positioning of those elements yourself, as in the example you linked, rather than trying to have the brush do it for you.
