### ISSUE TITLE
Brush doesn’t prevent scrolling on touch devices.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-brush#45]
It’s impossible to move a brush vertically on touch devices because it doesn’t appear to be preventing the page from scrolling from moving the brush.

**Comment by mbostock** [comment]
Possibly we need touch-action: none, too.

**Comment by mbostock** [comment]
The only thing that we’re missing here is that we’re calling `nopropagation` on touchstart rather than `noevent`, and that’s due to d3/d3-drag#9. But as long as the user isn’t trying to support clicking and brushing simultaneously, it should be safe to `noevent` on touchstart and thus prevent scrolling. Brushing is essentially unusable on touch devices now, so I think we must start there.

**Comment by mbostock** [comment]
> as long as the user isn’t trying to support clicking and brushing simultaneously

It seems like that works, though. You can listen to *click* events as long as the click gesture didn’t have any effect on the brush (*e.g.*, clicking on the background when the brush is empty, or clicking on the brush but not moving during click).

That means we might want to take the more conservative route and only preventDefault on mousedown for touch devices.

**Comment by mbostock** [comment]
I must be missing something here: d3-drag also does not preventDefault on touchstart or mousedown, but it works on iOS.

**Comment by mbostock** [comment]
I’ve isolated the issue: it’s because for d3-brush, the touchmove listener isn’t registered until touchstart, whereas for d3-drag and d3-zoom, the touchmove listener is registered once ahead of time. 🤦‍♂ 

https://observablehq.com/d/e3dc7fb1297975f8

**Comment by mbostock** [comment]
Some history.

d3.brush previously registered the touch listeners statically; they were switched to transient listeners in https://github.com/d3/d3/commit/6ef0eda53f4f70fc8c0b38a5b1b1f1505bcbf22e. Prior to that, d3.brush registered listeners statically on the window! That was removed in https://github.com/d3/d3/commit/ec12de6eec51e01935449770ee3b0add0241865e.

d3.drag adopted static touch listeners in https://github.com/d3/d3-drag/commit/94967422d32368373987faf1407a34c2c530de69.

d3.zoom appears to have always used static touch listeners since the first commit, https://github.com/d3/d3/commit/2d98bf10a4b4e41c5df54e0a1febb22ab687c48f.

**Comment by yaahor** [comment]
It works properly if brush is applied to the `<svg>` element, but `<g>` element.
