### ISSUE TITLE
Translate d3.svg.brush code to d3-brush?

### ISSUE THREAD

**Issue by pjm17971** [d3/d3-brush#8]
Trying out the version of this library pushed to npm yesterday. My code, like [most d3 brush code](http://jsfiddle.net/HCF9x/1/) to control the time axis of a chart, looks more or less like this:
```
var timeScale = d3.time.scale()...
var brush = d3.svg.brush()
    .x(timeScale)
    .on("brush", brushed);
```
There doesn't seem to be an [x(scale)](https://github.com/d3/d3/wiki/SVG-Controls#brush_x) method on brush anymore. Is there an example anywhere?

My actual code is [here](https://github.com/esnet/react-timeseries-charts/blob/master/src/brush.jsx#L33).

**Comment by mbostock** [comment]
I’m still working on it. I’ll post examples and documentation soon. Please be patient.

**Comment by AjayDevJ** [comment]
Any example posted on this? Any example two dimensional brush not with pixel value instead x y values??
