### ISSUE TITLE
Error multitouch emit undefined inside move function

### ISSUE THREAD

**Issue by jjjkolkh** [d3/d3-brush#83]
When using a device with multitouch I get an error when outside the chart something is pressed first and held down and afterwards pressing inside the chart.
The error is as following:
TypeError: Cannot read property 'brush' of undefined
TypeError: emitter(...).moved is not a function
TypeError: emitter(...).ended is not a function

Tracing the issue in the D3 bundle I found out that the move function is called before the emit variable is set:
![image](https://user-images.githubusercontent.com/12096831/110610631-b65fc180-818e-11eb-93e7-cedc4fb7a7d6.png)

Online debug information:
ContextListener is called first with a TouchStart event
![image](https://user-images.githubusercontent.com/12096831/110609741-d0e56b00-818d-11eb-93af-3e0ab8aea9c8.png)

Then inside the started function the move function will be called
![image](https://user-images.githubusercontent.com/12096831/110609880-fa05fb80-818d-11eb-9be8-a448da6d720f.png)

Inside move function the emit variable is undefined, hence throwing the error
![image](https://user-images.githubusercontent.com/12096831/110610114-3174a800-818e-11eb-8718-7513f646ecbd.png)

**Comment by jjjkolkh** [comment]
See the following file:
[D3issue.zip](https://github.com/d3/d3-brush/files/6121215/D3issue.zip)

In here I replicate how the XYChart is being handled in my application.

**Comment by Fil** [comment]
Can you please confirm that https://github.com/d3/d3-brush/pull/84 would resolve this issue?

**Comment by jjjkolkh** [comment]
Sure, thanks!
I need the touch panel to test it for sure though, so I'll do it on Monday morning as it's in the office.

**Comment by jjjkolkh** [comment]
Hi Fil,
I can verify that on my system the error is now gone!
It's also behaving as expected.

**Comment by Fil** [comment]
Excellent! Thank you for the feedback.

**Comment by Fil** [comment]
Please share a webpage or an observable notebook that exhibits the issue.

**Comment by dronesflier** [comment]
I've created a PR that fixed this on my end (example site: https://neuburg-donau.info/erleben/wandern/rundwanderweg-alte-burg_id9791, ISN'T MERGED YET; this is simply a demonstration of it NOT working.)
